when@dev:
    web_profiler:
        toolbar: true
        intercept_redirects: false

    framework:
<<<<<<< HEAD
        profiler:
            only_exceptions: false

=======
        profiler: { only_exceptions: false }
>>>>>>> origin/blog1

when@test:
    web_profiler:
        toolbar: false
        intercept_redirects: false

    framework:
        profiler: { collect: false }
