home:
    path: /
    controller: App\Controller\HomeController::index

    # config/routes.yaml
statistics:
    path: /statistics
    controller: App\Controller\ServiceController::index
back:
    path: /services/back
    controller: App\Controller\ServiceBackController::index




