home:
    path: /
    controller: App\Controller\HomeController::index
search_courses:
    path: /courses/search
    methods: [POST]
pdf:
    path: /pdf
    controller: App\Controller\CourseController::pdf
back:
    path: /courses/back
    controller: App\Controller\CourseBackController::index
statistics:
    path: /statistics
    controller: App\Controller\ServiceController::index
backend:
    path: /services/back
    controller: App\Controller\ServiceBackController::index

