home:
    path: /
    controller: App\Controller\HomeController::index

    # config/routes.yaml
statistics:
    path: /statistics
    controller: App\Controller\ServiceController::index
back:
    path: /services/back
    controller: App\Controller\ServiceBackController::index

add_service_json_new:
    path: /addServiceJson/new
    controller: App\Controller\Service1Controller::new
    methods: [GET]

delete_service_json:
    path: /DeleteServiceJson/{id}
    controller: App\Controller\Service1Controller::delete
    methods: GET