home:
    path: /
    controller: App\Controller\HomeController::index
<<<<<<< HEAD

    # config/routes.yaml
statistics:
    path: /statistics
    controller: App\Controller\ServiceController::index


=======
search_courses:
    path: /courses/search
    methods: [POST]
>>>>>>> origin/Course
