<?php

namespace ContainerP8EB5WO;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_FvkWU6gService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.FvkWU6g' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.FvkWU6g'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'lesson' => ['privates', '.errored..service_locator.FvkWU6g.App\\Entity\\Lesson', NULL, 'Cannot autowire service ".service_locator.FvkWU6g": it references class "App\\Entity\\Lesson" but no such service exists.'],
            'lessonRepository' => ['privates', 'App\\Repository\\LessonRepository', 'getLessonRepositoryService', true],
        ], [
            'lesson' => 'App\\Entity\\Lesson',
            'lessonRepository' => 'App\\Repository\\LessonRepository',
        ]);
    }
}
