<?php

namespace ContainerP8EB5WO;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_CRM_O5SService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.CRM.O5S' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.CRM.O5S'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'App\\Controller\\CourseController::delete' => ['privates', '.service_locator.TCOXoT8', 'get_ServiceLocator_TCOXoT8Service', true],
            'App\\Controller\\CourseController::edit' => ['privates', '.service_locator.TCOXoT8', 'get_ServiceLocator_TCOXoT8Service', true],
            'App\\Controller\\CourseController::index' => ['privates', '.service_locator.w07iIQI', 'get_ServiceLocator_W07iIQIService', true],
            'App\\Controller\\CourseController::indexFront' => ['privates', '.service_locator.w07iIQI', 'get_ServiceLocator_W07iIQIService', true],
            'App\\Controller\\CourseController::new' => ['privates', '.service_locator.w07iIQI', 'get_ServiceLocator_W07iIQIService', true],
            'App\\Controller\\CourseController::show' => ['privates', '.service_locator.lShnJV_', 'get_ServiceLocator_LShnJVService', true],
            'App\\Controller\\LessonController::delete' => ['privates', '.service_locator.FvkWU6g', 'get_ServiceLocator_FvkWU6gService', true],
            'App\\Controller\\LessonController::edit' => ['privates', '.service_locator.FvkWU6g', 'get_ServiceLocator_FvkWU6gService', true],
            'App\\Controller\\LessonController::index' => ['privates', '.service_locator.5EKs91d', 'get_ServiceLocator_5EKs91dService', true],
            'App\\Controller\\LessonController::new' => ['privates', '.service_locator.5EKs91d', 'get_ServiceLocator_5EKs91dService', true],
            'App\\Controller\\LessonController::show' => ['privates', '.service_locator.7BmVW2x', 'get_ServiceLocator_7BmVW2xService', true],
            'App\\Kernel::loadRoutes' => ['privates', '.service_locator.xUrKPVU', 'get_ServiceLocator_XUrKPVUService', true],
            'App\\Kernel::registerContainerConfiguration' => ['privates', '.service_locator.xUrKPVU', 'get_ServiceLocator_XUrKPVUService', true],
            'kernel::loadRoutes' => ['privates', '.service_locator.xUrKPVU', 'get_ServiceLocator_XUrKPVUService', true],
            'kernel::registerContainerConfiguration' => ['privates', '.service_locator.xUrKPVU', 'get_ServiceLocator_XUrKPVUService', true],
            'App\\Controller\\CourseController:delete' => ['privates', '.service_locator.TCOXoT8', 'get_ServiceLocator_TCOXoT8Service', true],
            'App\\Controller\\CourseController:edit' => ['privates', '.service_locator.TCOXoT8', 'get_ServiceLocator_TCOXoT8Service', true],
            'App\\Controller\\CourseController:index' => ['privates', '.service_locator.w07iIQI', 'get_ServiceLocator_W07iIQIService', true],
            'App\\Controller\\CourseController:indexFront' => ['privates', '.service_locator.w07iIQI', 'get_ServiceLocator_W07iIQIService', true],
            'App\\Controller\\CourseController:new' => ['privates', '.service_locator.w07iIQI', 'get_ServiceLocator_W07iIQIService', true],
            'App\\Controller\\CourseController:show' => ['privates', '.service_locator.lShnJV_', 'get_ServiceLocator_LShnJVService', true],
            'App\\Controller\\LessonController:delete' => ['privates', '.service_locator.FvkWU6g', 'get_ServiceLocator_FvkWU6gService', true],
            'App\\Controller\\LessonController:edit' => ['privates', '.service_locator.FvkWU6g', 'get_ServiceLocator_FvkWU6gService', true],
            'App\\Controller\\LessonController:index' => ['privates', '.service_locator.5EKs91d', 'get_ServiceLocator_5EKs91dService', true],
            'App\\Controller\\LessonController:new' => ['privates', '.service_locator.5EKs91d', 'get_ServiceLocator_5EKs91dService', true],
            'App\\Controller\\LessonController:show' => ['privates', '.service_locator.7BmVW2x', 'get_ServiceLocator_7BmVW2xService', true],
            'kernel:loadRoutes' => ['privates', '.service_locator.xUrKPVU', 'get_ServiceLocator_XUrKPVUService', true],
            'kernel:registerContainerConfiguration' => ['privates', '.service_locator.xUrKPVU', 'get_ServiceLocator_XUrKPVUService', true],
        ], [
            'App\\Controller\\CourseController::delete' => '?',
            'App\\Controller\\CourseController::edit' => '?',
            'App\\Controller\\CourseController::index' => '?',
            'App\\Controller\\CourseController::indexFront' => '?',
            'App\\Controller\\CourseController::new' => '?',
            'App\\Controller\\CourseController::show' => '?',
            'App\\Controller\\LessonController::delete' => '?',
            'App\\Controller\\LessonController::edit' => '?',
            'App\\Controller\\LessonController::index' => '?',
            'App\\Controller\\LessonController::new' => '?',
            'App\\Controller\\LessonController::show' => '?',
            'App\\Kernel::loadRoutes' => '?',
            'App\\Kernel::registerContainerConfiguration' => '?',
            'kernel::loadRoutes' => '?',
            'kernel::registerContainerConfiguration' => '?',
            'App\\Controller\\CourseController:delete' => '?',
            'App\\Controller\\CourseController:edit' => '?',
            'App\\Controller\\CourseController:index' => '?',
            'App\\Controller\\CourseController:indexFront' => '?',
            'App\\Controller\\CourseController:new' => '?',
            'App\\Controller\\CourseController:show' => '?',
            'App\\Controller\\LessonController:delete' => '?',
            'App\\Controller\\LessonController:edit' => '?',
            'App\\Controller\\LessonController:index' => '?',
            'App\\Controller\\LessonController:new' => '?',
            'App\\Controller\\LessonController:show' => '?',
            'kernel:loadRoutes' => '?',
            'kernel:registerContainerConfiguration' => '?',
        ]);
    }
}
