<?php

namespace ContainerCtI89As;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_7BmVW2xService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.7BmVW2x' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.7BmVW2x'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'lesson' => ['privates', '.errored..service_locator.7BmVW2x.App\\Entity\\Lesson', NULL, 'Cannot autowire service ".service_locator.7BmVW2x": it references class "App\\Entity\\Lesson" but no such service exists.'],
        ], [
            'lesson' => 'App\\Entity\\Lesson',
        ]);
    }
}
