<?php

namespace ContainerCtI89As;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_TCOXoT8Service extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.TCOXoT8' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.TCOXoT8'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'course' => ['privates', '.errored..service_locator.TCOXoT8.App\\Entity\\Course', NULL, 'Cannot autowire service ".service_locator.TCOXoT8": it references class "App\\Entity\\Course" but no such service exists.'],
            'courseRepository' => ['privates', 'App\\Repository\\CourseRepository', 'getCourseRepositoryService', true],
        ], [
            'course' => 'App\\Entity\\Course',
            'courseRepository' => 'App\\Repository\\CourseRepository',
        ]);
    }
}
