<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerCsmPiKA\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerCsmPiKA/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerCsmPiKA.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerCsmPiKA\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerCsmPiKA\App_KernelDevDebugContainer([
    'container.build_hash' => 'CsmPiKA',
    'container.build_id' => 'e48d7e8c',
    'container.build_time' => 1683209880,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerCsmPiKA');
